// Generated by scripts/codegen.ts
// Do not edit this file directly.
import { KernelSpec } from "./kernel";
import { opSpecToKernelSpecs } from "../src/opgen";
import { registry as opRegistry } from "./op_table";

export const kernels: { [name: string]: KernelSpec } = {};

for (const [name, spec] of Object.entries(opRegistry)) {
    const specs = opSpecToKernelSpecs(spec);
    for (const spec of specs) {
        kernels[spec.name] = spec;
    }
}
